language: node_js
install:
- npm install
after_success:
- npm run snyk-monitor
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/789c495ac457dab0ae54
  on_success: always
  on_failure: always
node_js:
- 8
- 10
env:
  global:
    secure: jzR1fDj7QoL/xlpZeC5+d7QaIm6J5NXHGefUEsaJM+2oFi1E49hOqHxWtaQo0k6EGdHKZXdfGuht+kalRQ5UoRQToSt6NwIs+iK6aNO+noNrXN+IEP5mqFPMwhXDtSsXtfavpoMaK729ZCU6s8ASsaZKLNFY+CrxbSjzMOtjVmiMkG6kw9+UqlaBO6BWC3+Te/HmXta8wSI3Frsl93DmnwVS8F+obKzRegVEnRHilbcPfSJavszwe3ASal1q/ptB18RmCC0f6Et7ObVrT3oVK6cq97FycWToePwD2OD1z1Lrg5HJsYPcqWV1YAwMpa1Rp1P+SC0aVojMcwxP3FOaaIRYKhIjvodbRYNzY3UTlSHBMcwNH4hz6JhuPmZF9Qs8CDb2QjuVjaHxZq/+C+Wzu+eklJeU1vpTnBtuhlfNTI5KNG3TVczSy1PbA6KRKESmj2VGgLGGKfY77DWE9CL9V98t9+183qcBTl07IKTQlCOILhVJtL/mBs8nxj25ZpyTfv2ZMkxg1QqJQsqyxt/W2NPlDjIr4RWt4vbSpfKr3t5RJ/FSILUUh0NiL/wMh6ZcKmDp+YdwE4e0ZBTLB5mzEU658owA6e/ndlJrG7DRFahCtHoSIK6PQc9nwsR1WzNx2kZ4X7187EgQMmFONqQ225R7Kcapvcbc2q9t9CdsmPw=
